### ISSUE TITLE
Datagrid-Filter

### ISSUE THREAD

**Issue by PatrickHeusinger** [dttctcs/seidr-react#45]
Customer says: 

In Findings on right-side filter, for the Patch Available and Severity we have in drop-down list possibilities of "Smaller equal" and Greater equal". May be confusing to user.
Suggest change to "Smaller or equal to" and "Greater or equal to"

DEADLINE in the next three weeks.

**Comment by Thames1990** [comment]
@PatrickHeusinger this has to be done with babel translations: https://python-babel.github.io/flask-babel/#using-translations

You have to create a translations file with your desired results for `Smaller equal` and so on.
